# Generated by Django 4.2.7 on 2023-11-06 12:29

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='arquivos_exames/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_autenticacao',
            fields=[
                ('id_usuario_autenticacao', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=500)),
                ('sobrenome', models.CharField(max_length=500)),
                ('celular', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('senha', models.CharField(max_length=500)),
                ('data_criacao', models.DateTimeField()),
                ('data_finalizacao_cadastro', models.DateTimeField()),
                ('ultima_edicao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuario_autenticacao',
            },
        ),
        migrations.CreateModel(
            name='Usuario_exame_arquivo',
            fields=[
                ('id_exame_arquivo', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario_autenticacao', models.IntegerField()),
                ('laudo', models.CharField(blank=True, max_length=500)),
                ('nome_exame', models.CharField(blank=True, max_length=500)),
                ('nome_arquivo', models.CharField(blank=True, max_length=500)),
                ('extensao', models.CharField(blank=True, max_length=500)),
                ('profissional', models.CharField(blank=True, max_length=500)),
                ('data_realizacao', models.CharField(blank=True, max_length=500)),
                ('id_laboratorio_possui_usuario', models.IntegerField()),
                ('status_exame', models.IntegerField()),
                ('comentarios_recusa', models.CharField(blank=True, default=None, max_length=500)),
            ],
            options={
                'db_table': 'usuario_exame_arquivo',
            },
        ),
        migrations.CreateModel(
            name='Usuario_configuracao',
            fields=[
                ('id_usuario_configuracao', models.AutoField(primary_key=True, serialize=False)),
                ('endereco', models.JSONField()),
                ('nacionalidade', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=50, unique=True)),
                ('genero', models.CharField(max_length=50)),
                ('nome_social', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField(blank=True, default=None)),
                ('tema', models.CharField(max_length=10)),
                ('id_usuario_autenticacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario_autenticacao')),
            ],
            options={
                'db_table': 'usuario_configuracao',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
