# Generated by Django 4.2.7 on 2023-11-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usuario_exame_arquivo_comentarios_recusa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario_autenticacao',
            name='data_finalizacao_cadastro',
        ),
        migrations.RemoveField(
            model_name='usuario_configuracao',
            name='tema',
        ),
        migrations.AlterField(
            model_name='usuario_autenticacao',
            name='celular',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usuario_autenticacao',
            name='email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usuario_autenticacao',
            name='nome',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usuario_autenticacao',
            name='senha',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usuario_autenticacao',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usuario_configuracao',
            name='cpf',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario_configuracao',
            name='data_nascimento',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usuario_configuracao',
            name='endereco',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario_configuracao',
            name='genero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario_configuracao',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario_configuracao',
            name='nome_social',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
